language: swift
osx_image: xcode11.3

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=Example/AlamofireRSSParser.xcworkspace
    - IOS_SDK=iphonesimulator13.2
  matrix:
    - SCHEME="AlamofireRSSParser-Example"

before_install:
  - gem install cocoapods --no-ri --no-document --quiet

script:
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk "$IOS_SDK" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build
